name: Yarn Lint

on: [pull_request, workflow_dispatch]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
  
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint
